trigger:
- main  # Cambia a tu rama si usas otra

pool:
  name: Default  # Asegúrate que sea el pool donde está tu agente local

variables:
  JMETER_VERSION: '5.5'
  JMETER_FOLDER: 'apache-jmeter-$(JMETER_VERSION)'

steps:

- powershell: |
    Write-Host "Descargando Apache JMeter..."
    Invoke-WebRequest -Uri "https://downloads.apache.org/jmeter/binaries/apache-jmeter-$(JMETER_VERSION).zip" -OutFile "$(JMETER_FOLDER).zip"
    Expand-Archive -Path "$(JMETER_FOLDER).zip" -DestinationPath .
  displayName: 'Descargar JMeter'

- powershell: |
    Write-Host "Ejecutando prueba JMeter..."
    .\$(JMETER_FOLDER)\bin\jmeter.bat -n -t pruebas\ScriptOrange.jmx -l resultados\resultados.jtl
  displayName: 'Ejecutar prueba JMeter'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'resultados'
    artifactName: 'ResultadosJMeter'
    publishLocation: 'Container'
  displayName: 'Publicar resultados'
