# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Cambia a la rama que uses

pool:
  vmImage: 'ubuntu-latest'

variables:
  JMETER_VERSION: '5.5'

steps:

- script: |
    echo "Descargando Apache JMeter..."
    wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-$(JMETER_VERSION).tgz
    tar -xvzf apache-jmeter-$(JMETER_VERSION).tgz
  displayName: 'Descargar JMeter'

- script: |
    echo "Ejecutando prueba JMeter..."
    ./apache-jmeter-$(JMETER_VERSION)/bin/jmeter -n -t pruebas/ScriptOrange.jmx -l resultados/resultados.jtl
  displayName: 'Ejecutar prueba JMeter'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'resultados'
    artifactName: 'ResultadosJMeter'
    publishLocation: 'Container'
  displayName: 'Publicar resultados'